### ISSUE TITLE
Make 'official' release

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/borg-space#1]
There are currently no releases tagged. I'm about to package this up for Alpine, so it'd be good to have an 'official' release to build against, and use its version number.

**Comment by KenKundert** [comment]
Okay, I have added a tag for this release.  Thanks for adding both emborg and borg-space to Alpine.

**Comment by adhawkins** [comment]
Thanks. Hopefully Alpine will accept 0.0 as a valid version! :)

**Comment by adhawkins** [comment]
Ok, all packaged up. Will upload now.
