### ISSUE TITLE
Add option to write plot to a file

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/borg-space#3]
If running borg-space in a console, using '-g' doesn't seem to do anything.

**Comment by KenKundert** [comment]
Easily done, is SVG okay?

**Comment by adhawkins** [comment]
No real preference as to format, whatever the library supports that has good support in most OSs

**Comment by KenKundert** [comment]
I have updated github.  You can now add `--svg bs.svg` to the command line and *borg-space* will save the graph to a file rather than try to display it (in this case use of -g is not necessary).  Give it a try, if you like it I will release this version to pypi.

**Comment by adhawkins** [comment]
Aside from the fact I have very little data to view, it looks good to me. Thanks!

**Comment by KenKundert** [comment]
The new version has been released to pypi.  Thanks for the suggestion.

**Comment by adhawkins** [comment]
Can you please label this release on GitHub too? Then I can package it up for Alpine.
