### ISSUE TITLE
Depends on emborg still?

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/borg-space#5]
Just wondering if this should still depend on emborg? The docs say it reads files created by emborg 1.36 to determine the space used, so surely this should still be a requirement?

**Comment by KenKundert** [comment]
The previous version of borg-space used the Emborg API and so it had a direct dependency on Emborg.  This version does not use the emborg API and so no longer has a direct dependency on the Emborg code.  Instead it counts on Emborg producing a particularly file when it performs a backup.  Only Emborg 1.36 and later creates that file.  Borg-Space can read those files on remote machines.  So it is possible to install Borg-Space on a machine, such as a laptop, that does not have Emborg installed, so as to be able to monitor the back-ups on other machines, say a collection of servers.  In that case forcing the installation of Emborg on the laptop would serve no purpose.

**Comment by adhawkins** [comment]
Ok, understood. Just wanted to be sure I set the dependencies of the Alpine correctly.

Thanks for the explanation.
