### ISSUE TITLE
Formatting of axis labels

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/borg-space#7]
While looking at getting the new version working, I've noticed that some of the axis labels aren't really readable:

A couple of examples:

Y axis:
![image](https://github.com/KenKundert/borg-space/assets/1628607/1d032c80-395b-4482-b77f-92fa25b1f1f8)

X axis:
![image](https://github.com/KenKundert/borg-space/assets/1628607/edd44cf8-0b70-4c64-a5f0-4bb37bad882b)

**Comment by KenKundert** [comment]
Unfortnately this a known issue with matplotlib.  There is not much I can do about it.

**Comment by adhawkins** [comment]
Would you consider a PR that changed borg-space to use a different graphics library? Maybe plotly?

**Comment by KenKundert** [comment]
Absolutely.  I have no experience with plotly.  I'd be interested in seeing how it compared.
