### ISSUE TITLE
borg-space doesn't handle config containing '-'

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/borg-space#9]
It appears that borg-space can't handle an emborg config containing a '-':

```
xcp-alpine-emborg:~# borg-space syno-docker
borg-space error: syno-docker: expected identifier
```

**Comment by KenKundert** [comment]
Thanks.  That will be fixed in the upcoming version.

**Comment by KenKundert** [comment]
This issue should be fixed in the new version on github.  Please give it a try and let me know how it works for you.

**Comment by adhawkins** [comment]
Can confirm this now seems to work Ok.
